use rand::{Rng, thread_rng};
use rand::prelude::SliceRandom;

use bookservice_repository::api::BookDetails;

#[test]
fn generate_lots_of_books_and_user_reservations() {
    const NO_OF_BOOKS_TO_GENERATE: usize = 1000;
    const NO_OF_AUTHORS_TO_GENERATE: usize = 100;

    let mut rng = thread_rng();

    let authors = generate_authors(&mut rng, NO_OF_AUTHORS_TO_GENERATE);
    let books = generate_books(&mut rng, NO_OF_BOOKS_TO_GENERATE, &authors);
}

fn generate_authors(rng: &mut impl Rng, no_of_authors: usize) -> Vec<String> {
    (0..no_of_authors)
        .map(|_| {
            format!(
                "{} {}",
                FIRST_NAMES.choose(rng).unwrap(),
                LAST_NAMES.choose(rng).unwrap()
            )
        })
        .collect()
}

fn generate_books(
    rng: &mut impl Rng,
    no_of_books_to_generate: usize,
    authors: &[String],
) -> Vec<BookDetails> {
    (0..no_of_books_to_generate)
        .map(|no| BookDetails {
            title: format!("A tale of number {} and {}", no, rng.gen_range(0..1000)),
            authors: (0..rng.gen_range(1..3))
                .map(|_| authors.choose(rng).unwrap())
                .cloned()
                .collect(),
            publisher: format!("Publisher {}", no % 20),
            description: "Some long description that is long".to_string(),
            tags: vec![],
        })
        .collect()
}

/// List of first names, based on most popular names list
const FIRST_NAMES: [&str; 142] = [
    "Ryan",
    "Dorothy",
    "Jacob",
    "Amy",
    "Nicholas",
    "Kathleen",
    "Gary",
    "Angela",
    "Eric",
    "Shirley",
    "Jonathan",
    "Emma",
    "Stephen",
    "Brenda",
    "Larry",
    "Pamela",
    "Justin",
    "Nicole",
    "Scott",
    "Anna",
    "Brandon",
    "Samantha",
    "Benjamin",
    "Katherine",
    "Samuel",
    "Christine",
    "Gregory",
    "Debra",
    "Alexander",
    "Rachel",
    "Patrick",
    "Carolyn",
    "Frank",
    "Janet",
    "Raymond",
    "Maria",
    "Jack",
    "Olivia",
    "Dennis",
    "Heather",
    "Jerry",
    "Helen",
    "Tyler",
    "Catherine",
    "Aaron",
    "Diane",
    "Jose",
    "Julie",
    "Adam",
    "Victoria",
    "Nathan",
    "Joyce",
    "Henry",
    "Lauren",
    "Zachary",
    "Kelly",
    "Douglas",
    "Christina",
    "Peter",
    "Ruth",
    "Kyle",
    "Joan",
    "Noah",
    "Virginia",
    "Ethan",
    "Judith",
    "Jeremy",
    "Evelyn",
    "Christian",
    "Hannah",
    "Walter",
    "Andrea",
    "Keith",
    "Megan",
    "Austin",
    "Cheryl",
    "Roger",
    "Jacqueline",
    "Terry",
    "Madison",
    "Sean",
    "Teresa",
    "Gerald",
    "Abigail",
    "Carl",
    "Sophia",
    "Dylan",
    "Martha",
    "Harold",
    "Sara",
    "Jordan",
    "Gloria",
    "Jesse",
    "Janice",
    "Bryan",
    "Kathryn",
    "Lawrence",
    "Ann",
    "Arthur",
    "Isabella",
    "Gabriel",
    "Judy",
    "Bruce",
    "Charlotte",
    "Logan",
    "Julia",
    "Billy",
    "Grace",
    "Joe",
    "Amber",
    "Alan",
    "Alice",
    "Juan",
    "Jean",
    "Elijah",
    "Denise",
    "Willie",
    "Frances",
    "Albert",
    "Danielle",
    "Wayne",
    "Marilyn",
    "Randy",
    "Natalie",
    "Mason",
    "Beverly",
    "Vincent",
    "Diana",
    "Liam",
    "Brittany",
    "Roy",
    "Theresa",
    "Bobby",
    "Kayla",
    "Caleb",
    "Alexis",
    "Bradley",
    "Doris",
    "Russell",
    "Lori",
    "Lucas",
    "Tiffany",
];

/// List of last names based on most popular last names
const LAST_NAMES: [&str; 127] = [
    "Wilson",
    "Moore",
    "Taylor",
    "Anderson",
    "Thomas",
    "Jackson",
    "White",
    "Harris",
    "Martin",
    "Thompson",
    "Garcia",
    "Martinez",
    "Robinson",
    "Clark",
    "Rodriguez",
    "Lewis",
    "Lee",
    "Walker",
    "Hall",
    "Allen",
    "Young",
    "Hernandez",
    "King",
    "Wright",
    "Lopez",
    "Hill",
    "Scott",
    "Green",
    "Adams",
    "Baker",
    "Gonzalez",
    "Nelson",
    "Carter",
    "Mitchell",
    "Perez",
    "Roberts",
    "Turner",
    "Phillips",
    "Campbell",
    "Parker",
    "Evans",
    "Edwards",
    "Collins",
    "Stewart",
    "Sanchez",
    "Morris",
    "Rogers",
    "Reed",
    "Cook",
    "Morgan",
    "Bell",
    "Murphy",
    "Bailey",
    "Rivera",
    "Cooper",
    "Richardson",
    "Cox",
    "Howard",
    "Ward",
    "Torres",
    "Peterson",
    "Gray",
    "Ramirez",
    "James",
    "Watson",
    "Brooks",
    "Kelly",
    "Sanders",
    "Price",
    "Bennett",
    "Wood",
    "Barnes",
    "Ross",
    "Henderson",
    "Coleman",
    "Jenkins",
    "Perry",
    "Powell",
    "Long",
    "Patterson",
    "Hughes",
    "Flores",
    "Washington",
    "Butler",
    "Simmons",
    "Foster",
    "Gonzales",
    "Bryant",
    "Alexander",
    "Russell",
    "Griffin",
    "Diaz",
    "Hayes",
    "Myers",
    "Ford",
    "Hamilton",
    "Graham",
    "Sullivan",
    "Wallace",
    "Woods",
    "Cole",
    "West",
    "Jordan",
    "Owens",
    "Reynolds",
    "Fisher",
    "Ellis",
    "Harrison",
    "Gibson",
    "Mcdonald",
    "Cruz",
    "Marshall",
    "Ortiz",
    "Gomez",
    "Murray",
    "Freeman",
    "Wells",
    "Webb",
    "Simpson",
    "Stevens",
    "Tucker",
    "Porter",
    "Hunter",
    "Hicks",
    "Crawford",
    "Henry",
    "Boyd",
];
